In [1]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
p = tf.placeholder('float', None)

In [3]:
operacao = p + 2

In [4]:
with tf.Session() as sess:
    resultado = sess.run(operacao, feed_dict = {p:[1,2,3]})

In [5]:
print(resultado)

[3. 4. 5.]


In [8]:
p2 = tf.placeholder('float', [None, 5])

In [11]:
operacao2 = p2 * 5

In [12]:
with tf.Session() as sess:
    dados = [[1,2,3,4,5], [6,7,8,9,10]]
    resultado2 = sess.run(operacao2, feed_dict = {p2: dados})
    print(resultado2)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
